const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const scope={window:{}};vm.createContext(scope);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','controller.js'),'utf8'),scope);
const {create,BUTTON}=scope.window.BlockController;
function pad(index=0,id='Steam Input Xbox',mapping='standard'){return {index,id,mapping,connected:true,axes:[0,0,0,0],buttons:Array.from({length:16},()=>({pressed:false,value:0}))};}
function press(p,i,down=true){p.buttons[i]={pressed:down,value:Number(down)};}
let checks=0;function check(label,test){test();checks++;console.log('PASS '+label);}
check('Sparse gamepad arrays and disconnection produce neutral movement',()=>{const c=create(),p=pad(2);p.axes[1]=-1;assert.equal(c.poll([null,null,p],0).move.y,-1);const s=c.poll([null,null,null],1);assert.equal(s.connected,false);assert.equal(s.move.y,0);assert.equal(s.down.size,0);});
check('Steam Input standard buttons map to all play controls',()=>{const c=create(),p=pad();c.poll([p],0);for(const i of Object.values(BUTTON)){press(p,i);const s=c.poll([p],1+i);assert.ok(s.pressed.has(i));assert.ok(s.down.has(i));press(p,i,false);c.poll([p],1.1+i);}});
check('Newly connected held buttons stay blocked until released and pressed again',()=>{const c=create(),p=pad();press(p,BUTTON.place);assert.equal(c.poll([p],0).down.size,0);assert.equal(c.poll([p],1).pressed.size,0);press(p,BUTTON.place,false);c.poll([p],2);press(p,BUTTON.place);assert.ok(c.poll([p],3).pressed.has(BUTTON.place));});
check('Changing from menu to play never carries a held confirm into building or jumping',()=>{const c=create(),p=pad();c.poll([p],0,'menu');press(p,BUTTON.jump);assert.ok(c.poll([p],1,'menu').pressed.has(BUTTON.jump));assert.equal(c.poll([p],1.01,'play').down.size,0);assert.equal(c.poll([p],2,'play').pressed.size,0);press(p,BUTTON.jump,false);c.poll([p],3);press(p,BUTTON.jump);assert.ok(c.poll([p],4).pressed.has(BUTTON.jump));});
check('Deadzone removes drift and keeps proportional analog movement',()=>{const c=create(),p=pad();p.axes=[.09,-.08,.12,-.04];let s=c.poll([p],0);assert.equal(s.move.x,0);assert.equal(s.look.y,0);p.axes=[.5,0,0,-.5];s=c.poll([p],1);assert.ok(s.move.x>.3&&s.move.x<.5);assert.ok(s.look.y<-.3&&s.look.y>-.5);});
check('Diagonal analog magnitude is clamped and malformed axes cannot poison the camera',()=>{const c=create(),p=pad();p.axes=[1,1,NaN,Infinity];const s=c.poll([p],0);assert.ok(Math.hypot(s.move.x,s.move.y)<=1.00001);assert.equal(s.look.x,0);assert.equal(s.look.y,0);});
check('Held triggers and menu arrows repeat at a bounded rate without burst catch-up',()=>{const c=create(),p=pad();c.poll([p],0);press(p,BUTTON.place);assert.ok(c.poll([p],.1).repeat.has(BUTTON.place));assert.equal(c.poll([p],.2).repeat.size,0);assert.ok(c.poll([p],.46).repeat.has(BUTTON.place));assert.equal(c.poll([p],.47).repeat.size,0);assert.equal(c.poll([p],100).repeat.size,1);assert.equal(c.poll([p],100.01).repeat.size,0);});
check('Nonstandard devices remain neutral unless their use is explicitly enabled',()=>{const c=create(),p=pad(0,'Raw joystick','');p.axes[0]=1;assert.equal(c.poll([p],0).usable,false);assert.equal(c.poll([p],1).move.x,0);assert.equal(c.poll([p],2,'play',{allowRaw:true}).move.x,1);});
check('The active device stays selected while additional controllers connect',()=>{const c=create(),first=pad(1),second=pad(0,'Other pad');assert.equal(c.poll([null,first],0).index,1);assert.equal(c.poll([second,first],1).index,1);first.connected=false;assert.equal(c.poll([second,first],2).index,0);});
check('A different device at the same slot cannot inherit a held action',()=>{const c=create(),p=pad();c.poll([p],0);press(p,BUTTON.gravity);assert.ok(c.poll([p],1).pressed.has(BUTTON.gravity));const replacement=pad(0,'Different controller');press(replacement,BUTTON.gravity);assert.equal(c.poll([replacement],2).pressed.size,0);});
check('Alternate look axes support joystick layouts and reset clears all held state',()=>{const c=create(),p=pad();p.axes=[0,0,0,.7,-.7];const s=c.poll([p],0,'play',{lookAxis:3});assert.ok(s.look.x>.6&&s.look.y<-.6);c.reset();press(p,BUTTON.remove);assert.equal(c.poll([p],1).down.size,0);});
console.log(`${checks} controller checks passed.`);
