const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(require('node:path').join(__dirname, '..', 'game.js'), 'utf8').replace(/\}\)\(\);\s*$/, `
  globalThis.testGame = { get, set, raycast, edit, undo, choose, saveNow, home, move, viewProjection, rebuild, player, keys, held,
    collides, lowerTo, raiseTo, positionAim, aimDirection, aimOffset, handleKeyDown, toggleGodView, toggleGravity, jump,
    switchArea, saveKey, pickBlock, renderPalette, updateBombs, bombs, frame, avatar, updateAvatar, cameraEye, preferences, toggleCamera, adjustZoom, faces, audio, toggleAudio,
    updateController, padMotion, updateQuests, updateQuestPanel, openModal,
    history: () => history,
    start: () => {started = true;$('welcome').classList.add('hidden');},
    stats: () => ({built, removed, blasted, questExpanded, colors: [...usedColors], achievements, changes, meshCount, falling, verticalVelocity, godView, currentArea, selected, paletteGroup}),
    reset: () => $('confirm-reset').onclick() };
})();`);
function boot(storage = new Map(), options = {thirdPerson:false}, AudioContext) {
  const elements = new Map();
  const listeners = new Map();
  const windowListeners = new Map();let pads=[];
  const timers = new Map();let nextTimer=1;
  const ctx2d = {setTransform(){},clearRect(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},stroke(){},fill(){},fillRect(){},fillText(){}};
  const gl = new Proxy({}, { get: (_, key) => {
    if (key === 'getShaderParameter' || key === 'getProgramParameter') return () => true;
    if (key === 'getAttribLocation') return () => 1;
    if (key === 'createProgram' || key === 'createShader' || key === 'createBuffer') return () => ({});
    return () => {};
  }});
  function classes(initial=[]) {const values=new Set(initial);return {add:n=>values.add(n),remove:n=>values.delete(n),contains:n=>values.has(n),toggle:(n,force)=>{const active=force??!values.has(n);if(active)values.add(n);else values.delete(n);return active;}};}
  function element(id) {
    if (!elements.has(id)) {
      const events=new Map(),attributes={};
      const el={id,textContent:'',style:{},dataset:{},classList:classes(['help-modal','reset-modal','controller-modal','extra-tools'].includes(id)?['hidden']:[]),
        addEventListener:(n,fn)=>events.set(n,fn),setAttribute:(n,v)=>attributes[n]=v,getAttribute:n=>attributes[n],appendChild(){},getContext:type=>type==='2d'?ctx2d:gl,
        focus(){context.document.activeElement=el;},click(){el.onclick?.();events.get('click')?.({target:el});},getClientRects:()=>[{}],
        querySelectorAll:()=>id==='help-modal'?[element('close-help')]:id==='reset-modal'?[element('cancel-reset'),element('confirm-reset')]:id==='controller-modal'?[element('controller-resume'),element('controller-area'),element('controller-gravity')]:[],
        dispatchEvent:e=>events.get(e.type)?.({target:el}),events,tagName:'BUTTON'};
      if(['area-select','controller-area','controller-profile','controller-look-axis'].includes(id)){
        el.tagName='SELECT';el.options=['cottage','street','volcano','meadow','titanic','cars','taipei101'].map(value=>({value}));let selectedIndex=0;
        Object.defineProperty(el,'selectedIndex',{get:()=>selectedIndex,set:v=>selectedIndex=v});
        Object.defineProperty(el,'value',{get:()=>el.options[selectedIndex]?.value,set:v=>{const i=el.options.findIndex(o=>o.value===v);if(i>=0)selectedIndex=i;}});
      }
      elements.set(id,el);
    }
    return elements.get(id);
  }
  const context = {document:{body:{classList:classes()},activeElement:null,visibilityState:'visible',getElementById:element,
    querySelector:()=>['welcome','help-modal','reset-modal','controller-modal'].map(element).find(e=>!e.classList.contains('hidden'))||null,
    querySelectorAll:selector=>selector==='[data-move]'?['rise-button','sink-button'].map(id=>{const el=element(id);el.dataset.move=id==='rise-button'?'rise':'sink';return el;}):[],
    createElement:()=>element('temp'+Math.random()),addEventListener:(name,fn)=>listeners.set(name,fn)},
    window:{devicePixelRatio:1,AudioContext,addEventListener:(n,fn)=>windowListeners.set(n,fn)},navigator:{getGamepads:()=>pads},Event:class{constructor(type){this.type=type;}},
    localStorage:{getItem:k=>storage.get(k)||(k==='little-block-world-settings-v1'&&options?JSON.stringify(options):null),setItem:(k,v)=>storage.set(k,v)},console,setTimeout:fn=>{const id=nextTimer++;timers.set(id,fn);return id;},clearTimeout:id=>timers.delete(id),requestAnimationFrame(){},innerWidth:1300,innerHeight:880};
  vm.createContext(context);for(const file of ['penguin.js','audio.js','controller.js'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'..',file),'utf8'),context);vm.runInContext(source,context);context.testGame.start();
  return {game:context.testGame,penguin:context.window.BlockPenguin,elements,storage,listeners,windowListeners,setPads:v=>pads=v,
    setModal:v=>element('help-modal').classList.toggle('hidden',!v),setHidden:v=>{context.document.visibilityState=v?'hidden':'visible';listeners.get('visibilitychange')();},flushTimers:()=>{const pending=[...timers.entries()];timers.clear();pending.forEach(([,fn])=>fn());}};
}
let checks=0;
function check(label, fn) { fn(); checks++; console.log('PASS '+label); }
const session=boot(),g=session.game;
check('Initial world includes a house, pond and protected foundation',()=>{assert.equal(g.get(18,5,18),8);assert.equal(g.get(10,1,21),10);assert.ok(g.get(20,0,20));});
check('Starting camera immediately targets a buildable surface',()=>{const hit=g.raycast();assert.ok(hit);assert.ok(hit.distance<16);assert.ok(hit.previous[1]>0);});
check('Projection is finite and mesh contains visible triangles',()=>{assert.ok([...g.viewProjection()].every(Number.isFinite));g.rebuild();assert.ok(g.stats().meshCount>1000);assert.equal(g.stats().meshCount%3,0);});
const target=Array.from(g.raycast().previous),previous=g.get(...target);
check('Place selected block and award the first star',()=>{g.choose(7);g.edit('place');assert.equal(g.get(...target),7);assert.equal(g.stats().built,1);assert.equal(g.stats().achievements,1);});
check('Undo restores the previous world state',()=>{g.undo();assert.equal(g.get(...target),previous);});
check('Remove block and undo removal',()=>{const hit=g.raycast(),xyz=Array.from(hit.xyz),type=hit.type;g.edit('remove');assert.equal(g.get(...xyz),0);g.undo();assert.equal(g.get(...xyz),type);});
check('Save and reload preserve construction and progress',()=>{g.choose(8);g.edit('place');g.saveNow();const again=boot(session.storage).game;assert.equal(again.get(...target),8);assert.equal(again.stats().built,2);});
check('Protected foundation cannot be removed',()=>{Object.assign(g.player,{x:1.5,y:3,z:1.5,pitch:-1.3,yaw:0});const hit=g.raycast();assert.ok(hit);assert.equal(hit.xyz[1],0);const before=g.get(...hit.xyz);g.edit('remove');assert.equal(g.get(...hit.xyz),before);});
check('Flight stops on release and stays within height limits',()=>{g.home();g.held.add('rise');for(let i=0;i<300;i++)g.move(.04);assert.ok(g.player.y<=38);g.held.clear();const height=g.player.y;g.move(.04);assert.equal(g.player.y,height);});
check('Movement respects island boundaries',()=>{Object.assign(g.player,{x:.5,y:17,z:.5,yaw:0});g.held.add('left');g.held.add('forward');for(let i=0;i<100;i++)g.move(.04);assert.ok(g.player.x>=.4 && g.player.z>=.4);g.held.clear();});
check('Malformed save does not prevent game startup',()=>{const s=new Map([['little-block-world-v1','{bad json']]);assert.ok(boot(s).game.raycast());});
check('Invalid save coordinates, foundation edits and unknown blocks are ignored',()=>{const s=new Map([['little-block-world-v1',JSON.stringify({version:1,changes:{'20,0,20':0,'100,4,5':7,'20,4,20':99,'19,4,20':7},built:-2,achievements:90})]]);const other=boot(s).game;assert.ok(other.get(20,0,20));assert.equal(other.get(19,4,20),7);assert.equal(other.stats().built,0);assert.equal(other.stats().achievements,3);});
check('Eight placements and three materials award all stars',()=>{g.home();for(let i=0;i<8;i++){g.choose([6,7,8][i%3]);g.edit('place');g.undo();}assert.ok(g.stats().built>=8);assert.equal(g.stats().achievements,3);});
check('Reset restores the original world and clears progress',()=>{g.reset();assert.equal(g.stats().built,0);assert.equal(g.stats().achievements,0);assert.equal(Object.keys(g.stats().changes).length,0);assert.equal(g.get(18,5,18),8);});
check('Context menu is blocked on the whole document',()=>{let prevented=false;session.listeners.get('contextmenu')({preventDefault:()=>prevented=true});assert.equal(prevented,true);});
check('Space flies in floating mode and one Shift press starts gravity with browser defaults prevented',()=>{g.home();const start=g.player.y;let prevented=false;g.handleKeyDown({code:'Space',repeat:false,timeStamp:1000,preventDefault:()=>prevented=true});g.move(.04);assert.ok(g.player.y>start);assert.ok(prevented);g.keys.clear();g.handleKeyDown({code:'ShiftLeft',repeat:false,timeStamp:2000,preventDefault(){}});const high=g.player.y;g.move(.04);assert.ok(g.player.y<high);assert.equal(g.preferences.gravity,true);g.keys.clear();g.toggleGravity();});
check('Mouse offset changes the actual ray direction and selected voxel',()=>{g.home();const first=g.raycast();g.positionAim(115,0);const second=g.raycast();assert.ok(second);assert.notEqual(first.xyz.join(','),second.xyz.join(','));assert.ok(g.aimDirection()[0]>0);g.positionAim(10000,0);assert.ok(Math.hypot(g.aimOffset.x,g.aimOffset.y)<=130.001);g.home();});
check('Off-center building and removal use the visible crosshair',()=>{g.home();g.positionAim(110,20);const xyz=Array.from(g.raycast().previous);g.choose(9);g.edit('place');assert.equal(g.get(...xyz),9);g.edit('remove');assert.equal(g.get(...xyz),0);g.home();});
check('Player walks under a one-block-high ceiling and stops at a wall',()=>{const tiny=boot().game;for(let x=14;x<=17;x++)for(let z=14;z<=16;z++)tiny.set(x,4,z,5);Object.assign(tiny.player,{x:13.5,y:3.722,z:15.5,yaw:0});assert.equal(tiny.collides(14.5,3.722,15.5),false);tiny.held.add('right');for(let i=0;i<12;i++)tiny.move(.04);assert.ok(tiny.player.x>15);assert.equal(tiny.player.y,3.722);tiny.set(16,3,15,5);for(let i=0;i<15;i++)tiny.move(.04);assert.ok(tiny.player.x<16);assert.equal(tiny.collides(tiny.player.x,tiny.player.y,tiny.player.z),false);});
function shift(game,time,repeat=false) {game.handleKeyDown({code:'ShiftLeft',timeStamp:time,repeat,preventDefault(){}});}
check('Shift toggles gravity once per separate press regardless of timing or key autorepeat',()=>{const f=boot().game;Object.assign(f.player,{x:25.5,y:15,z:25.5});shift(f,1000);assert.equal(f.preferences.gravity,true);shift(f,1100,true);shift(f,1200);assert.equal(f.preferences.gravity,true);f.move(.04);assert.equal(f.stats().falling,true);f.keys.clear();shift(f,9000);assert.equal(f.preferences.gravity,false);const height=f.player.y;for(let i=0;i<50;i++)f.move(.04);assert.equal(f.player.y,height);});
check('Gravity lands on solid ground and remains enabled without clipping through blocks',()=>{const f=boot().game;Object.assign(f.player,{x:25.5,y:18,z:25.5});shift(f,1000);f.keys.clear();for(let i=0;i<200;i++)f.move(.04);assert.equal(f.stats().falling,false);assert.equal(f.preferences.gravity,true);assert.ok(Math.abs(f.player.y-3.722)<1e-8);assert.equal(f.collides(f.player.x,f.player.y,f.player.z),false);});
check('Gravity lands on the roof including high-speed swept collision',()=>{const f=boot().game;Object.assign(f.player,{x:20.5,y:18,z:18.5});shift(f,1000);f.keys.clear();for(let i=0;i<200;i++)f.move(.04);assert.ok(Math.abs(f.player.y-10.722)<1e-8);assert.equal(f.stats().falling,false);});
check('Space boosts upward during a fall while keeping gravity enabled',()=>{const f=boot().game;shift(f,1000);f.keys.clear();for(let i=0;i<6;i++)f.move(.04);const low=f.player.y;f.handleKeyDown({code:'Space',timeStamp:1650,repeat:false,preventDefault(){}});f.move(.04);assert.ok(f.player.y>low);assert.equal(f.preferences.gravity,true);assert.equal(f.stats().falling,false);});
check('God view stays high, prevents editing, and returns exact position, direction and aim',()=>{g.home();g.positionAim(63,-27);Object.assign(g.player,{x:25.5,y:8.2,z:25.5,yaw:.51,pitch:-.23});const original=JSON.stringify(g.player),aim=JSON.stringify(g.aimOffset),before=Object.keys(g.stats().changes).length;g.toggleGodView();assert.equal(g.player.y,42);g.held.add('sink');g.move(.04);assert.equal(g.player.y,42);g.edit('place');assert.equal(Object.keys(g.stats().changes).length,before);g.player.yaw+=.6;g.toggleGodView();assert.equal(JSON.stringify(g.player),original);assert.equal(JSON.stringify(g.aimOffset),aim);assert.equal(g.stats().godView,null);});
check('Return home from God view resets view state and controls',()=>{g.toggleGodView();g.home();assert.equal(g.stats().godView,null);assert.equal(g.player.y,8);assert.equal(g.aimOffset.x,0);});
check('All seven regions have distinct terrain, safe starts and buildable targets',()=>{const a=boot().game;for(const id of ['cottage','street','volcano','meadow','titanic','cars','taipei101']){a.switchArea(id);assert.equal(a.stats().currentArea,id);assert.equal(a.collides(a.player.x,a.player.y,a.player.z),false);assert.ok(a.raycast(),id+' should have a starting target');}a.switchArea('street');assert.equal(a.get(17,2,35),14);assert.equal(a.get(27,5,5),8);a.switchArea('volcano');assert.equal(a.get(20,5,19),15);assert.equal(a.get(24,10,19),18);a.switchArea('meadow');for(let x=0;x<40;x++)for(let z=0;z<40;z++){assert.equal(a.get(x,2,z),1);for(let y=3;y<40;y++)assert.equal(a.get(x,y,z),0);}});
check('Region switch flushes pending writes, preserves blocks, stars and independent undo',()=>{const s=boot(),a=s.game;const cottageTarget=Array.from(a.raycast().previous);a.choose(7);a.edit('place');a.switchArea('street');s.flushTimers();assert.equal(a.stats().built,0);const beforeStreet=a.raycast().xyz.join(',');a.undo();assert.equal(a.raycast().xyz.join(','),beforeStreet);const streetTarget=Array.from(a.raycast().previous);a.choose(16);a.edit('place');a.switchArea('cottage');assert.equal(a.get(...cottageTarget),7);assert.equal(a.stats().achievements,1);assert.equal(a.stats().built,1);a.undo();assert.equal(a.get(...cottageTarget),0);a.switchArea('street');assert.equal(a.get(...streetTarget),16);assert.equal(a.stats().built,1);a.undo();assert.equal(a.get(...streetTarget),0);});
check('All regional construction and last chosen area survive a fresh session',()=>{const s=boot(),targets={};for(const id of ['cottage','street','volcano','meadow','titanic','cars','taipei101']){s.game.switchArea(id);targets[id]=Array.from(s.game.raycast().previous);s.game.choose(7);s.game.edit('place');s.game.saveNow();}const fresh=boot(s.storage).game;assert.equal(fresh.stats().currentArea,'taipei101');for(const id of ['cottage','street','volcano','meadow','titanic','cars','taipei101']){fresh.switchArea(id);assert.equal(fresh.get(...targets[id]),7);assert.equal(fresh.stats().built,1);assert.equal(fresh.stats().achievements,1);}});
check('New World restores only the current region and leaves every other saved region byte-identical',()=>{const s=boot(),a=s.game;for(const id of ['cottage','street','volcano','meadow','titanic','cars','taipei101']){a.switchArea(id);a.choose(7);a.edit('place');a.saveNow();}a.switchArea('volcano');const others=['cottage','street','meadow','titanic','cars','taipei101'].map(id=>[id,s.storage.get(a.saveKey(id))]);a.reset();assert.equal(a.stats().built,0);assert.equal(a.get(20,5,19),15);for(const [id,raw]of others)assert.equal(s.storage.get(a.saveKey(id)),raw);const fresh=boot(s.storage).game;fresh.switchArea('volcano');assert.equal(fresh.stats().built,0);for(const [id]of others){fresh.switchArea(id);assert.equal(fresh.stats().built,1);assert.equal(fresh.stats().achievements,1);}});
check('Legacy cottage save migrates without changing its backup and cannot reappear after reset',()=>{const legacy=JSON.stringify({version:1,changes:{'19,4,20':7},built:8,colors:[6,7,8],achievements:3});const s=boot(new Map([['little-block-world-v1',legacy]])),a=s.game;assert.equal(a.get(19,4,20),7);assert.equal(a.stats().achievements,3);assert.equal(s.storage.get('little-block-world-v1'),legacy);assert.equal(JSON.parse(s.storage.get(a.saveKey())).version,2);a.switchArea('meadow');a.reset();a.switchArea('cottage');assert.equal(a.get(19,4,20),7);a.reset();a.switchArea('street');a.switchArea('cottage');assert.equal(a.get(19,4,20),0);assert.equal(boot(s.storage).game.get(19,4,20),0);assert.equal(s.storage.get('little-block-world-v1'),legacy);});
check('The same coordinates can hold different materials in different regions',()=>{const s=boot(),a=s.game;Object.assign(a.player,{x:20.5,y:4.722,z:20.5,pitch:-1.2});a.switchArea('meadow');const xyz=Array.from(a.raycast().previous);a.choose(8);a.edit('place');a.switchArea('street');const before=a.get(...xyz);assert.notEqual(before,8);a.switchArea('meadow');assert.equal(a.get(...xyz),8);});
check('In-memory regional work remains isolated when localStorage writes fail',()=>{class FailingStorage extends Map{set(){throw Error('Quota exceeded');}}const s=boot(new FailingStorage()),a=s.game;const xyz=Array.from(a.raycast().previous);a.choose(7);a.edit('place');assert.equal(a.saveNow(),false);a.switchArea('meadow');a.choose(8);a.edit('place');a.switchArea('cottage');assert.equal(a.get(...xyz),7);assert.equal(a.stats().built,1);a.switchArea('meadow');assert.equal(a.stats().built,1);});
check('R selects generated materials and number keys match the current palette tab',()=>{const a=boot().game;a.switchArea('street');a.pickBlock();assert.equal(a.stats().selected,a.raycast().type);a.renderPalette('nature');a.handleKeyDown({code:'Digit7',key:'7',repeat:false,timeStamp:2000,preventDefault(){}});assert.equal(a.stats().selected,18);a.renderPalette('building');a.handleKeyDown({code:'Digit7',key:'7',repeat:false,timeStamp:3000,preventDefault(){}});assert.equal(a.stats().selected,17);});
check('God view is excluded from saved positions and changing regions exits it',()=>{const s=boot(),a=s.game;const before={...a.player};a.toggleGodView();a.saveNow();const payload=JSON.parse(s.storage.get(a.saveKey()));assert.equal(payload.player.y,before.y);a.switchArea('volcano');assert.equal(a.stats().godView,null);assert.equal(a.player.y,17.5);a.switchArea('cottage');assert.equal(a.player.y,before.y);});
check('Invalid region selection or mismatched save identity cannot replace another region',()=>{const s=boot(),a=s.game;a.switchArea('__proto__');assert.equal(a.stats().currentArea,'cottage');s.storage.set(a.saveKey('meadow'),JSON.stringify({version:2,area:'street',changes:{'20,3,20':7},built:4}));a.switchArea('meadow');assert.equal(a.stats().built,0);assert.equal(a.get(20,3,20),0);});
function plant(game,area='meadow',type=19) {
  game.switchArea(area);game.choose(type);const xyz=Array.from(game.raycast().previous);game.edit('place');
  assert.equal(game.get(...xyz),type);assert.equal(game.bombs.get(xyz.join(',')).remaining,10);return xyz;
}
function worldState(game){const result=[];for(let y=0;y<40;y++)for(let z=0;z<40;z++)for(let x=0;x<40;x++)result.push(game.get(x,y,z));return result;}
check('Landmarks have four funnels, different vehicles and an eight-tier tower with a tall spire',()=>{const a=boot().game;a.switchArea('titanic');for(const z of [12,17,22,26]){assert.equal(a.get(20,14,z),9);assert.equal(a.get(20,17,z),18);}assert.equal(a.get(15,5,20),14);a.switchArea('cars');assert.equal(a.get(19,6,25),9);assert.equal(a.get(29,7,29),16);assert.equal(a.get(24,9,30),14);a.switchArea('taipei101');for(let i=0;i<8;i++)assert.equal(a.get(16,10+i*3,20),20);assert.equal(a.get(20,38,20),12);assert.equal(a.get(20,4,25),0);a.rebuild();assert.ok(a.stats().meshCount>1000);});
check('Bomb placement arms exactly ten seconds and explodes only when the countdown ends',()=>{const a=boot().game,xyz=plant(a);a.updateBombs(9);assert.equal(a.get(...xyz),19);assert.equal(a.bombs.get(xyz.join(',')).remaining,1);a.updateBombs(.5);assert.equal(a.get(...xyz),19);a.updateBombs(.5);assert.equal(a.get(...xyz),0);assert.equal(a.bombs.size,0);assert.equal(a.history().at(-1).kind,'explosion');});
check('Blast removes a two-block sphere, leaves its foundation and distant blocks intact, and never moves the player',()=>{const a=boot().game,[x,y,z]=plant(a);for(const [dx,dy,dz]of [[2,0,0],[2,1,0],[-2,0,0],[0,0,2],[1,1,1]])a.set(x+dx,y+dy,z+dz,6);const camera=JSON.stringify(a.player),base=worldState(a).slice(0,1600);a.updateBombs(10);assert.equal(a.get(x+2,y,z),0);assert.equal(a.get(x+2,y+1,z),6);assert.equal(a.get(x-2,y,z),0);assert.equal(a.get(x+1,y+1,z+1),0);assert.equal(JSON.stringify(a.player),camera);assert.deepEqual(worldState(a).slice(0,1600),base);});
check('One undo restores the entire explosion and disarms restored bombs',()=>{const a=boot().game,xyz=plant(a);const before=worldState(a);a.updateBombs(10);assert.notDeepEqual(worldState(a),before);a.undo();assert.deepEqual(worldState(a),before);assert.equal(a.get(...xyz),19);assert.equal(a.bombs.size,0);a.updateBombs(30);assert.deepEqual(worldState(a),before);a.undo();assert.equal(a.get(...xyz),0);});
check('Removing a live bomb cancels it; undoing removal restores a stopped bomb',()=>{const a=boot().game,xyz=plant(a);a.updateBombs(3);a.edit('remove');assert.equal(a.get(...xyz),0);assert.equal(a.bombs.size,0);a.undo();assert.equal(a.get(...xyz),19);assert.equal(a.bombs.size,0);const before=worldState(a);a.updateBombs(20);assert.deepEqual(worldState(a),before);});
check('Undoing a bomb placement cancels its future explosion',()=>{const a=boot().game;plant(a);a.undo();const before=worldState(a);a.updateBombs(20);assert.equal(a.bombs.size,0);assert.deepEqual(worldState(a),before);});
check('Nearby bombs extend the blast through a chain while distant timers continue',()=>{const a=boot().game,[x,y,z]=plant(a);for(const offset of [1,3,10]){const xyz=[x+offset,y,z];a.set(...xyz,19);a.bombs.set(xyz.join(','),{xyz,remaining:10});}a.set(x+5,y,z,6);const before=worldState(a);a.bombs.get([x,y,z].join(',')).remaining=1;a.updateBombs(1);assert.equal(a.get(x+1,y,z),0);assert.equal(a.get(x+3,y,z),0);assert.equal(a.get(x+5,y,z),0);assert.equal(a.get(x+10,y,z),19);assert.equal(a.bombs.size,1);assert.equal(a.bombs.get([x+10,y,z].join(',')).remaining,9);assert.equal(a.history().filter(i=>i.kind==='explosion').length,1);a.undo();assert.deepEqual(worldState(a),before);assert.equal(a.bombs.size,1);assert.equal(a.bombs.get([x+10,y,z].join(',')).remaining,9);a.updateBombs(1);for(const offset of [0,1,3])assert.equal(a.get(x+offset,y,z),19);});
check('Five- and ten-block bombs each count ten seconds and remove their own spherical radius',()=>{for(const [type,radius,diagonal]of [[21,5,[3,4,0]],[22,10,[6,8,0]]]){const a=boot().game,[x,y,z]=plant(a,'meadow',type);for(const [dx,dy,dz]of [[radius,0,0],[radius,1,0],[radius+1,0,0],diagonal])a.set(x+dx,y+dy,z+dz,6);const before=worldState(a),camera=JSON.stringify(a.player);a.updateBombs(9);assert.equal(a.get(x,y,z),type);assert.equal(a.bombs.get([x,y,z].join(',')).remaining,1);a.updateBombs(1);assert.equal(a.get(x,y,z),0);assert.equal(a.get(x+radius,y,z),0);assert.equal(a.get(x+radius,y+1,z),6);assert.equal(a.get(x+radius+1,y,z),6);assert.equal(a.get(x+diagonal[0],y+diagonal[1],z),0);assert.deepEqual(worldState(a).slice(0,1600),before.slice(0,1600));assert.equal(JSON.stringify(a.player),camera);a.undo();assert.deepEqual(worldState(a),before);assert.equal(a.bombs.size,0);a.updateBombs(20);assert.deepEqual(worldState(a),before);}});
check('Mixed bomb sizes propagate using each triggered radius and one undo restores the entire chain',()=>{const a=boot().game,[x,y,z]=plant(a);for(const [offset,type]of [[2,21],[7,22],[-10,19]]){const xyz=[x+offset,y,z];a.set(...xyz,type);a.bombs.set(xyz.join(','),{xyz,remaining:10});}a.set(x+17,y,z,7);a.set(x+18,y,z,8);const before=worldState(a);a.bombs.get([x,y,z].join(',')).remaining=1;a.updateBombs(1);for(const offset of [0,2,7,17])assert.equal(a.get(x+offset,y,z),0);assert.equal(a.get(x+18,y,z),8);assert.equal(a.bombs.size,1);assert.equal(a.bombs.get([x-10,y,z].join(',')).remaining,9);const item=a.history().at(-1);assert.equal(item.kind,'explosion');assert.equal(new Set(item.edits.map(e=>e.xyz.join(','))).size,item.edits.length);a.undo();assert.deepEqual(worldState(a),before);assert.equal(a.bombs.size,1);});
check('Overlapping bombs that expire together explode once each and produce one reversible chain',()=>{const s=boot(),a=s.game,[x,y,z]=plant(a);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const xyz=[x+dx,y,z+dz];a.set(...xyz,19);a.bombs.set(xyz.join(','),{xyz,remaining:10});}const before=worldState(a);a.updateBombs(10);assert.equal(a.bombs.size,0);assert.equal(a.history().filter(i=>i.kind==='explosion').length,1);assert.match(s.elements.get('toast').textContent,/5 顆/);const edits=a.history().at(-1).edits;assert.equal(new Set(edits.map(e=>e.xyz.join(','))).size,edits.length);a.undo();assert.deepEqual(worldState(a),before);a.updateBombs(10);assert.deepEqual(worldState(a),before);});
check('Large explosions at world corners stay within bounds and preserve the protected foundation',()=>{for(const xyz of [[0,1,0],[39,39,39]]){const a=boot().game;a.switchArea('meadow');a.set(...xyz,22);a.bombs.set(xyz.join(','),{xyz,remaining:1});const before=worldState(a);a.updateBombs(1);assert.equal(a.get(...xyz),0);assert.deepEqual(worldState(a).slice(0,1600),before.slice(0,1600));for(const e of a.history().at(-1).edits)assert.ok(e.xyz.every((n,i)=>n>=0&&n<40&&(i!==1||n>0)));a.undo();assert.deepEqual(worldState(a),before);}});
check('A stopped bomb stays idle by itself but another blast can ignite it',()=>{const a=boot().game,[x,y,z]=plant(a);a.set(x+2,y,z,21);a.set(x+7,y,z,6);assert.equal(a.bombs.size,1);a.updateBombs(10);assert.equal(a.get(x+2,y,z),0);assert.equal(a.get(x+7,y,z),0);a.undo();assert.equal(a.get(x+2,y,z),21);assert.equal(a.bombs.size,0);a.updateBombs(30);assert.equal(a.get(x+2,y,z),21);assert.equal(a.get(x+7,y,z),6);});
check('New bomb variants save their type, selection and countdown in independent regions across reloads',()=>{const s=boot(),a=s.game,positions=[];for(const [area,type]of [['meadow',21],['cars',22],['cottage',19]]){const xyz=plant(a,area,type);a.updateBombs(3);positions.push({area,type,xyz});}a.saveNow();const fresh=boot(s.storage).game;for(const {area,type,xyz}of positions){fresh.switchArea(area);assert.equal(fresh.get(...xyz),type);assert.equal(fresh.stats().selected,type);assert.equal(fresh.stats().paletteGroup,'fun');assert.equal(fresh.bombs.get(xyz.join(',')).remaining,7);}fresh.switchArea('meadow');const other=s.storage.get(fresh.saveKey('cars'));fresh.updateBombs(7);fresh.saveNow();assert.equal(s.storage.get(fresh.saveKey('cars')),other);fresh.switchArea('cars');assert.equal(fresh.bombs.get(positions[1].xyz.join(',')).remaining,7);fresh.reset();assert.equal(fresh.bombs.size,0);fresh.switchArea('cottage');assert.equal(fresh.bombs.get(positions[2].xyz.join(',')).remaining,7);});
check('Number keys select all three bomb sizes and the displayed range follows the selection',()=>{const s=boot(),a=s.game;a.renderPalette('fun');for(const [key,type,radius]of [['1',19,2],['2',21,5],['3',22,10]]){a.handleKeyDown({code:'Digit'+key,key,repeat:false,timeStamp:2000,preventDefault(){}});assert.equal(a.stats().selected,type);assert.ok(s.elements.get('palette-note').textContent.includes('半徑 '+radius+' 格'));}});
check('Countdown pauses behind dialogs and in hidden tabs, then resumes without counting hidden time',()=>{const s=boot(),a=s.game,xyz=plant(a);a.frame(1000);a.frame(3000);assert.equal(a.bombs.get(xyz.join(',')).remaining,8);s.setModal(true);a.frame(13000);assert.equal(a.bombs.get(xyz.join(',')).remaining,8);s.setModal(false);a.frame(14000);assert.equal(a.bombs.get(xyz.join(',')).remaining,7);s.setHidden(true);a.frame(20000);assert.equal(a.bombs.get(xyz.join(',')).remaining,7);s.setHidden(false);a.frame(90000);a.frame(91000);assert.equal(a.bombs.get(xyz.join(',')).remaining,6);});
check('Each area preserves its remaining countdown independently, including across reloads',()=>{const s=boot(),a=s.game,meadow=plant(a);a.updateBombs(4);const ship=plant(a,'titanic');a.updateBombs(2);a.switchArea('meadow');assert.equal(a.bombs.get(meadow.join(',')).remaining,6);a.switchArea('titanic');assert.equal(a.bombs.get(ship.join(',')).remaining,8);a.saveNow();const fresh=boot(s.storage).game;assert.equal(fresh.stats().currentArea,'titanic');assert.equal(fresh.bombs.get(ship.join(',')).remaining,8);fresh.switchArea('meadow');assert.equal(fresh.bombs.get(meadow.join(',')).remaining,6);fresh.updateBombs(6);fresh.switchArea('titanic');assert.equal(fresh.get(...ship),19);assert.equal(fresh.bombs.get(ship.join(',')).remaining,8);});
check('Reset clears only current bombs and retains the other region countdown and saved bytes',()=>{const s=boot(),a=s.game;const meadow=plant(a);a.updateBombs(3);plant(a,'cars');const raw=s.storage.get(a.saveKey('meadow'));a.reset();assert.equal(a.bombs.size,0);assert.equal(s.storage.get(a.saveKey('meadow')),raw);a.switchArea('meadow');assert.equal(a.get(...meadow),19);assert.equal(a.bombs.get(meadow.join(',')).remaining,7);});
check('Invalid saved timers do not arm unknown, out-of-range or stopped blocks',()=>{const payload={version:2,area:'meadow',changes:{'10,4,10':19},bombs:[{xyz:[10,4,10],remaining:99},{xyz:[9,4,9],remaining:5},{xyz:[10,4,10],remaining:-1},{xyz:[10,4,10],remaining:'5'},{xyz:[10,4,10,10],remaining:5}],selected:19};const a=boot(new Map([['little-block-world-area-v2','meadow'],['little-block-world-v2:meadow',JSON.stringify(payload)]])).game;assert.equal(a.get(10,4,10),19);assert.equal(a.bombs.size,0);assert.equal(a.stats().paletteGroup,'fun');a.updateBombs(100);assert.equal(a.get(10,4,10),19);});
check('Countdown edits and grouped explosion undo remain isolated in memory when storage fails',()=>{class FailingStorage extends Map{set(){throw Error('Quota exceeded');}}const s=boot(new FailingStorage()),a=s.game,xyz=plant(a);a.updateBombs(2);a.switchArea('cars');a.switchArea('meadow');assert.equal(a.bombs.get(xyz.join(',')).remaining,8);const before=worldState(a);a.updateBombs(8);a.switchArea('cars');a.switchArea('meadow');a.undo();assert.deepEqual(worldState(a),before);assert.equal(a.bombs.size,0);});
check('High flying camera and construction above the old ceiling survive a fresh session',()=>{const s=boot(),a=s.game;a.switchArea('taipei101');Object.assign(a.player,{x:29.5,y:36,z:30.5,yaw:-.73,pitch:-.42});const xyz=Array.from(a.raycast().previous);assert.ok(xyz[1]>24);a.choose(7);a.edit('place');assert.equal(a.get(...xyz),7);a.saveNow();const fresh=boot(s.storage).game;assert.equal(fresh.get(...xyz),7);assert.equal(fresh.player.y,36);fresh.toggleGodView();assert.equal(fresh.player.y,70);assert.ok([...fresh.viewProjection()].every(Number.isFinite));fresh.toggleGodView();assert.equal(fresh.player.y,36);});

check('New players start with the visible penguin, optional audio off and a safe default zoom',()=>{const a=boot(new Map(),null).game;assert.equal(a.preferences.thirdPerson,true);assert.equal(a.preferences.sfx,false);assert.equal(a.preferences.music,false);assert.equal(a.preferences.distance,3.6);assert.ok(a.cameraEye().clearance>3);assert.notEqual(a.cameraEye().z,a.player.z);});
check('Third-person starting views remain safe and aim at a buildable target in every region',()=>{const a=boot(new Map(),null).game;for(const id of ['cottage','street','volcano','meadow','titanic','cars','taipei101']){a.switchArea(id);const e=a.cameraEye();assert.equal(a.get(Math.floor(e.x),Math.floor(e.y),Math.floor(e.z)),0,id);assert.ok(a.raycast(),id);assert.equal(a.collides(a.player.x,a.player.y,a.player.z),false);}});
check('Penguin triangles remain finite, below one block and inside the short body height through every animation',()=>{const s=boot(),a=s.game;for(const mode of ['idle','walk','rise','sink','fall','hover'])for(let i=0;i<36;i++){const pose={phase:i*Math.PI/9,[mode]:1,landing:i%2,action:i%3/2};const vertices=s.penguin.geometry(pose,{x:0,y:0,z:0},i*.13,a.faces);assert.equal(vertices.length%30,0);for(let v=0;v<vertices.length;v+=10){assert.ok(Number.isFinite(vertices[v]));assert.ok(vertices[v+1]>=-.001);assert.ok(vertices[v+1]<.82,mode+': '+vertices[v+1]);assert.equal(vertices[v+8],0);}}});
check('Walking, rising, descending, hovering and landing respond to real movement and blend smoothly',()=>{const a=boot().game;a.switchArea('meadow');a.held.add('forward');for(let i=0;i<10;i++){a.move(.04);a.updateAvatar(.04);}assert.equal(a.avatar.mode,'walk');assert.ok(a.avatar.walk>.9);const heading=a.avatar.heading;a.held.clear();a.held.add('right');a.move(.04);a.updateAvatar(.04);assert.ok(a.avatar.heading>heading&&a.avatar.heading<Math.PI/2);a.held.clear();a.held.add('rise');for(let i=0;i<10;i++){a.move(.04);a.updateAvatar(.04);}assert.equal(a.avatar.mode,'rise');assert.ok(a.avatar.rise>.9);a.held.clear();a.move(.04);a.updateAvatar(.04);assert.equal(a.avatar.mode,'hover');a.held.add('sink');for(let i=0;i<10;i++){a.move(.04);a.updateAvatar(.04);}assert.equal(a.avatar.mode,'idle');assert.ok(a.avatar.landing>0);a.held.clear();});
check('Gravity falling spreads the penguin wings and landing recovers without camera physics changes',()=>{const a=boot().game;a.switchArea('meadow');Object.assign(a.player,{x:25.5,y:10,z:25.5});a.updateAvatar(.04);shift(a,1000);a.keys.clear();a.move(.04);a.updateAvatar(.04);assert.equal(a.avatar.mode,'fall');for(let i=0;i<100;i++){a.move(.04);a.updateAvatar(.04);}assert.equal(a.avatar.mode,'idle');assert.ok(Math.abs(a.player.y-3.722)<1e-8);});
check('Camera retracts before walls and tunnel ceilings while the short penguin still fits underneath',()=>{const a=boot(new Map(),null).game;a.switchArea('meadow');Object.assign(a.player,{x:20.5,y:3.722,z:20.5,yaw:0,pitch:0});const open=a.cameraEye().clearance;for(let x=19;x<=22;x++)for(let y=3;y<7;y++)a.set(x,y,22,5);const e=a.cameraEye();assert.ok(e.clearance<open);assert.ok(e.z<21.93);for(let x=19;x<=22;x++)for(let z=19;z<=21;z++)a.set(x,4,z,5);assert.equal(a.collides(20.5,3.722,20.5),false);const low=a.cameraEye();assert.equal(a.get(Math.floor(low.x),Math.floor(low.y),Math.floor(low.z)),0);});
check('Third-person placement and removal track the projected crosshair even after zooming',()=>{const a=boot(new Map(),null).game;a.switchArea('meadow');a.positionAim(65,35);a.adjustZoom(1);a.frame(1000);for(let i=1;i<80;i++)a.frame(1000+i*20);const h=a.raycast();assert.ok(h);a.choose(7);a.edit('place');assert.equal(a.get(...h.previous),7);a.edit('remove');assert.equal(a.get(...h.previous),0);const eye=a.cameraEye(),dir=a.aimDirection(),vp=a.viewProjection();const point=[eye.x+dir[0]*10,eye.y+dir[1]*10,eye.z+dir[2]*10,1],clip=[0,0,0,0];for(let r=0;r<4;r++)for(let k=0;k<4;k++)clip[r]+=vp[k*4+r]*point[k];assert.ok(Math.abs(clip[0]/clip[3]*650-a.aimOffset.x)<.001);assert.ok(Math.abs(-clip[1]/clip[3]*440-a.aimOffset.y)<.001);});
check('Zoom clamps, first-person zoom matches aiming, and God zoom never changes the saved penguin position',()=>{const s=boot(new Map(),null),a=s.game,position=JSON.stringify(a.player);a.adjustZoom(-100);assert.equal(a.preferences.distance,1.4);assert.equal(JSON.stringify(a.player),position);a.adjustZoom(100);assert.equal(a.preferences.distance,7.5);a.toggleCamera();assert.equal(a.cameraEye().x,a.player.x);assert.ok([...a.viewProjection()].every(Number.isFinite));a.switchArea('taipei101');const physical=JSON.stringify(a.player);a.toggleGodView();a.adjustZoom(-100);assert.ok(a.player.y>=44);a.saveNow();assert.equal(JSON.stringify(JSON.parse(s.storage.get(a.saveKey())).player),physical);a.toggleGodView();assert.equal(JSON.stringify(a.player),physical);});
check('Camera and volume preferences survive reload and New World does not change them',()=>{const s=boot(new Map(),null),a=s.game;a.toggleCamera();a.adjustZoom(.7);a.preferences.volume=.3;a.adjustZoom(0);const fresh=boot(s.storage,null).game;assert.equal(fresh.preferences.thirdPerson,false);assert.equal(fresh.preferences.distance,4.3);assert.equal(fresh.preferences.volume,.3);fresh.reset();assert.equal(fresh.preferences.distance,4.3);});
function space(game,repeat=false){game.handleKeyDown({code:'Space',repeat,preventDefault(){}});}
check('A held Space makes one gravity jump and settles without repeated jumping',()=>{const a=boot().game;a.switchArea('meadow');a.toggleGravity();const ground=a.player.y;space(a);let peak=ground;for(let i=0;i<100;i++){space(a,true);a.move(.04);peak=Math.max(peak,a.player.y);}assert.ok(peak>ground+1&&peak<ground+2);assert.ok(Math.abs(a.player.y-ground)<1e-8);assert.equal(a.preferences.gravity,true);});
check('Separate Space presses boost through the air and release allows natural landing',()=>{const a=boot().game;a.switchArea('meadow');a.toggleGravity();const ground=a.player.y;for(let jumpIndex=0;jumpIndex<8;jumpIndex++){a.keys.delete('Space');space(a);for(let i=0;i<4;i++)a.move(.04);}assert.ok(a.player.y>ground+6);a.keys.clear();for(let i=0;i<200;i++)a.move(.04);assert.ok(Math.abs(a.player.y-ground)<1e-8);});
check('Jump sweeps stop below a low ceiling and the short body still fits the tunnel',()=>{const a=boot().game;a.switchArea('meadow');Object.assign(a.player,{x:20.5,y:3.722,z:20.5});a.set(20,4,20,5);a.toggleGravity();space(a);let highest=0;for(let i=0;i<70;i++){a.move(.04);highest=Math.max(highest,a.player.y);assert.equal(a.collides(a.player.x,a.player.y,a.player.z),false);}assert.ok(highest<=3.89801);assert.ok(Math.abs(a.player.y-3.722)<1e-8);});
check('Walking off a platform continues falling after landing because gravity remains on',()=>{const a=boot().game;a.switchArea('meadow');a.set(20,5,20,5);Object.assign(a.player,{x:20.5,y:6.722,z:20.5,yaw:0});a.toggleGravity();for(let i=0;i<20;i++)a.move(.04);assert.ok(Math.abs(a.player.y-6.722)<1e-8);a.keys.add('KeyW');for(let i=0;i<8;i++)a.move(.04);a.keys.clear();for(let i=0;i<100;i++)a.move(.04);assert.ok(Math.abs(a.player.y-3.722)<1e-8);assert.equal(a.preferences.gravity,true);});
check('The downward helper and C remain usable for floating flight',()=>{const s=boot(),a=s.game;a.switchArea('meadow');Object.assign(a.player,{y:12});a.handleKeyDown({code:'KeyC',repeat:false,preventDefault(){}});a.move(.04);assert.ok(a.player.y<12);a.keys.clear();const low=a.player.y;a.held.add('sink');a.move(.04);assert.ok(a.player.y<low);a.held.clear();assert.equal(a.preferences.gravity,false);});
check('Gravity and controller preferences survive reload, area switching and reset',()=>{const s=boot(),a=s.game;a.toggleGravity();a.preferences.controllerSensitivity=1.4;a.preferences.controllerDeadzone=.2;a.preferences.controllerProfile='gamepad';a.preferences.controllerAllowRaw=true;a.adjustZoom(0);a.switchArea('meadow');a.reset();const fresh=boot(s.storage).game;assert.equal(fresh.preferences.gravity,true);assert.equal(fresh.preferences.controllerSensitivity,1.4);assert.equal(fresh.preferences.controllerDeadzone,.2);assert.equal(fresh.preferences.controllerProfile,'gamepad');assert.equal(fresh.preferences.controllerAllowRaw,true);});
check('Menus, hidden pages and focus loss pause gravity and do not accumulate a large resume fall',()=>{const s=boot(),a=s.game;a.switchArea('meadow');a.player.y=18;a.toggleGravity();a.frame(1000);a.frame(1040);const y=a.player.y;s.setModal(true);a.frame(9000);assert.equal(a.player.y,y);s.setModal(false);s.setHidden(true);a.frame(20000);assert.equal(a.player.y,y);s.setHidden(false);a.frame(90000);assert.equal(a.player.y,y);s.windowListeners.get('blur')();a.frame(120000);assert.equal(a.player.y,y);s.windowListeners.get('focus')();a.frame(180000);assert.equal(a.player.y,y);a.frame(180040);assert.ok(a.player.y<y&&a.player.y>y-.2);});
check('Touch jump uses press edges in gravity mode and held flight in floating mode',()=>{const s=boot(),a=s.game;a.switchArea('meadow');a.toggleGravity();const button=s.elements.get('rise-button');button.setPointerCapture=()=>{};const event={pointerId:1,preventDefault(){}};button.events.get('pointerdown')(event);a.move(.04);assert.ok(a.player.y>3.722);for(let i=0;i<100;i++)a.move(.04);assert.ok(Math.abs(a.player.y-3.722)<1e-8);button.events.get('pointerup')();button.events.get('pointerdown')(event);a.move(.04);assert.ok(a.player.y>3.722);button.events.get('pointerup')();});
check('All three achievements automatically collapse but can reopen without losing statistics',()=>{const s=boot(),a=s.game;for(let i=0;i<8;i++){a.choose([6,7,8][i%3]);a.edit('place');a.undo();}assert.equal(a.stats().achievements,3);assert.equal(a.stats().questExpanded,false);assert.ok(s.elements.get('quest-body').classList.contains('hidden'));assert.equal(s.elements.get('built-count').textContent,'8');s.elements.get('quest-toggle').onclick();assert.equal(a.stats().questExpanded,true);a.choose(9);a.edit('place');assert.equal(a.stats().questExpanded,true);});
check('Placement and manual removal counters count successful actions and undo never erases activity',()=>{const s=boot(),a=s.game;a.choose(7);a.edit('place');a.edit('remove');assert.equal(a.stats().built,1);assert.equal(a.stats().removed,1);a.undo();assert.equal(a.stats().removed,1);assert.equal(s.elements.get('removed-count').textContent,'1');a.undo();assert.equal(a.stats().built,1);const n=a.stats().removed;a.toggleGodView();a.edit('remove');assert.equal(a.stats().removed,n);});
check('A whole chain counts each exploded block once and restores the world without decrementing totals',()=>{const a=boot().game,[x,y,z]=plant(a);a.set(x+1,y,z,21);a.set(x+3,y,z,22);a.updateBombs(10);const count=a.history().at(-1).edits.length;assert.equal(a.stats().blasted,count);assert.ok(count>100);a.undo();assert.equal(a.stats().blasted,count);assert.equal(a.get(x+1,y,z),21);});
check('Activity counters remain independent across regions, reloads, resets and legacy saves',()=>{const s=boot(),a=s.game;a.edit('place');a.edit('remove');assert.equal(a.stats().removed,1);a.switchArea('meadow');plant(a);a.updateBombs(10);const blasted=a.stats().blasted;a.saveNow();const fresh=boot(s.storage).game;assert.equal(fresh.stats().blasted,blasted);assert.equal(fresh.stats().removed,0);fresh.switchArea('cottage');assert.equal(fresh.stats().removed,1);fresh.reset();assert.equal(fresh.stats().removed,0);fresh.switchArea('meadow');assert.equal(fresh.stats().blasted,blasted);const old=boot(new Map([['little-block-world-v1',JSON.stringify({version:1,changes:{},built:3})]])).game;assert.equal(old.stats().removed,0);assert.equal(old.stats().blasted,0);});
function fakePad(){return {index:0,id:'Steam Input Xbox Controller',mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array.from({length:16},()=>({pressed:false,value:0}))};}
function padButton(p,index,pressed){p.buttons[index]={pressed,value:Number(pressed)};}
check('Analog movement stays proportional and diagonal movement cannot exceed walking speed',()=>{const a=boot().game;a.switchArea('meadow');const p=fakePad();p.axes=[.5,0,0,0];a.updateController(.04,0,[p]);const x=a.player.x;a.move(.04);assert.ok(a.player.x-x>.04&&a.player.x-x<.1);p.axes=[1,-1,0,0];const pos={...a.player};a.updateController(.04,1,[p]);a.move(.04);assert.ok(Math.hypot(a.player.x-pos.x,a.player.z-pos.z)<=.168001);});
check('Right joystick rotates the real aiming camera and recenters a mouse-offset crosshair',()=>{const s=boot(),a=s.game,p=fakePad();a.positionAim(80,40);p.axes[2]=1;p.axes[3]=-.6;const before={...a.player};a.updateController(.04,0,[p]);assert.ok(a.player.yaw>before.yaw);assert.ok(a.player.pitch>before.pitch);assert.equal(a.aimOffset.x,0);assert.equal(a.aimOffset.y,0);assert.equal(s.elements.get('place-key').textContent,'(RT)');assert.ok(a.raycast());});
check('Controller B toggles once while held and controller A only boosts on separate gravity presses',()=>{const a=boot().game,p=fakePad();a.switchArea('meadow');a.updateController(.04,0,[p]);padButton(p,1,true);a.updateController(.04,.1,[p]);assert.equal(a.preferences.gravity,true);a.updateController(.04,.8,[p]);assert.equal(a.preferences.gravity,true);padButton(p,1,false);a.updateController(.04,.9,[p]);padButton(p,0,true);a.updateController(.04,1,[p]);a.move(.04);assert.ok(a.player.y>3.722);for(let i=0;i<100;i++){a.updateController(.04,1.1+i*.04,[p]);a.move(.04);}assert.ok(Math.abs(a.player.y-3.722)<1e-8);padButton(p,0,false);a.updateController(.04,6,[p]);padButton(p,0,true);a.updateController(.04,6.1,[p]);a.move(.04);assert.ok(a.player.y>3.722);});
check('Controller triggers place and remove the actual raycast target with bounded repeats',()=>{const a=boot().game,p=fakePad();a.switchArea('meadow');a.choose(7);a.updateController(.04,0,[p]);const xyz=Array.from(a.raycast().previous);padButton(p,7,true);a.updateController(.04,.1,[p]);assert.equal(a.get(...xyz),7);assert.equal(a.stats().built,1);a.updateController(.04,.2,[p]);assert.equal(a.stats().built,1);padButton(p,7,false);a.updateController(.04,.3,[p]);padButton(p,6,true);a.updateController(.04,.4,[p]);assert.equal(a.get(...xyz),0);assert.equal(a.stats().removed,1);});
check('Controller shoulders, dpad and face buttons switch materials, groups, zoom, view and undo',()=>{const a=boot().game,p=fakePad();a.updateController(.04,0,[p]);const start=a.stats().selected;padButton(p,5,true);a.updateController(.04,.1,[p]);assert.notEqual(a.stats().selected,start);padButton(p,5,false);a.updateController(.04,.2,[p]);padButton(p,15,true);a.updateController(.04,.3,[p]);assert.equal(a.stats().paletteGroup,'building');padButton(p,15,false);a.updateController(.04,.4,[p]);const distance=a.preferences.distance;padButton(p,12,true);a.updateController(.04,.5,[p]);assert.ok(a.preferences.distance<distance);padButton(p,12,false);a.updateController(.04,.6,[p]);padButton(p,3,true);a.updateController(.04,.7,[p]);assert.equal(a.preferences.thirdPerson,true);});
check('Gamepad menus stop movement, B returns without toggling gravity, and held A does not jump on return',()=>{const s=boot(),a=s.game,p=fakePad();a.switchArea('meadow');a.updateController(.04,0,[p]);padButton(p,9,true);a.updateController(.04,.1,[p]);assert.equal(s.elements.get('controller-modal').classList.contains('hidden'),false);padButton(p,9,false);a.updateController(.04,.2,[p]);padButton(p,0,true);a.updateController(.04,.3,[p]);assert.equal(s.elements.get('controller-modal').classList.contains('hidden'),true);a.updateController(.04,.4,[p]);a.move(.04);assert.ok(Math.abs(a.player.y-3.722)<1e-8);padButton(p,0,false);a.updateController(.04,.5,[p]);a.openModal('controller-modal');a.updateController(.04,.6,[p]);padButton(p,1,true);a.updateController(.04,.7,[p]);assert.equal(s.elements.get('controller-modal').classList.contains('hidden'),true);assert.equal(a.preferences.gravity,false);});
check('Controller region navigation previews a selection and only A commits the world change',()=>{const s=boot(),a=s.game,p=fakePad();a.updateController(.04,0,[p]);a.openModal('controller-modal');a.updateController(.04,.1,[p]);padButton(p,13,true);a.updateController(.04,.2,[p]);padButton(p,13,false);a.updateController(.04,.3,[p]);padButton(p,15,true);a.updateController(.04,.4,[p]);assert.equal(s.elements.get('controller-area').value,'street');assert.equal(a.stats().currentArea,'cottage');padButton(p,15,false);a.updateController(.04,.5,[p]);padButton(p,0,true);a.updateController(.04,.6,[p]);assert.equal(a.stats().currentArea,'street');assert.equal(s.elements.get('controller-modal').classList.contains('hidden'),true);});
check('Disconnected or background controllers cannot keep moving or place a block on reconnect',()=>{const s=boot(),a=s.game,p=fakePad();a.switchArea('meadow');s.setPads([p]);a.frame(1000);p.axes[1]=-1;padButton(p,7,true);a.frame(1040);const built=a.stats().built;s.setHidden(true);a.frame(2000);const pos={...a.player};a.frame(9000);assert.deepEqual({...a.player},pos);s.setHidden(false);a.frame(10000);assert.equal(a.stats().built,built);s.setPads([]);a.frame(10040);const stopped={...a.player};a.frame(10080);assert.deepEqual({...a.player},stopped);});
console.log(`${checks} behavioral checks passed.`);
