const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(require('node:path').join(__dirname, '..', 'game.js'), 'utf8').replace(/\}\)\(\);\s*$/, `
  globalThis.testGame = { get, set, raycast, edit, undo, choose, saveNow, home, move, viewProjection, rebuild, player, keys, held,
    collides, lowerTo, positionAim, aimDirection, aimOffset, handleKeyDown, toggleGodView,
    switchArea, saveKey, pickBlock, renderPalette,
    start: () => started = true,
    stats: () => ({built, colors: [...usedColors], achievements, changes, meshCount, falling, godView, currentArea, selected, paletteGroup}),
    reset: () => $('confirm-reset').onclick() };
})();`);
function boot(storage = new Map()) {
  const elements = new Map();
  const listeners = new Map();
  const timers = new Map();let nextTimer=1;
  const ctx2d = {setTransform(){},clearRect(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},stroke(){}};
  const gl = new Proxy({}, { get: (_, key) => {
    if (key === 'getShaderParameter' || key === 'getProgramParameter') return () => true;
    if (key === 'getAttribLocation') return () => 1;
    if (key === 'createProgram' || key === 'createShader' || key === 'createBuffer') return () => ({});
    return () => {};
  }});
  function element(id) {
    if (!elements.has(id)) elements.set(id, {textContent:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(){},appendChild(){},getContext:type=>type==='2d'?ctx2d:gl});
    return elements.get(id);
  }
  const context = {document:{getElementById:element,querySelector:()=>null,querySelectorAll:()=>[],createElement:()=>element('temp'+Math.random()),addEventListener:(name,fn)=>listeners.set(name,fn)},window:{devicePixelRatio:1,addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},console,setTimeout:fn=>{const id=nextTimer++;timers.set(id,fn);return id;},clearTimeout:id=>timers.delete(id),requestAnimationFrame(){},innerWidth:1300,innerHeight:880};
  vm.createContext(context);vm.runInContext(source,context);context.testGame.start();
  return {game:context.testGame,elements,storage,listeners,flushTimers:()=>{const pending=[...timers.entries()];timers.clear();pending.forEach(([,fn])=>fn());}};
}
let checks=0;
function check(label, fn) { fn(); checks++; console.log('PASS '+label); }
const session=boot(),g=session.game;
check('Initial world includes a house, pond and protected foundation',()=>{assert.equal(g.get(18,5,18),8);assert.equal(g.get(10,1,21),10);assert.ok(g.get(20,0,20));});
check('Starting camera immediately targets a buildable surface',()=>{const hit=g.raycast();assert.ok(hit);assert.ok(hit.distance<16);assert.ok(hit.previous[1]>0);});
check('Projection is finite and mesh contains visible triangles',()=>{assert.ok([...g.viewProjection()].every(Number.isFinite));g.rebuild();assert.ok(g.stats().meshCount>1000);assert.equal(g.stats().meshCount%3,0);});
const target=Array.from(g.raycast().previous),previous=g.get(...target);
check('Place selected block and award the first star',()=>{g.choose(7);g.edit('place');assert.equal(g.get(...target),7);assert.equal(g.stats().built,1);assert.equal(g.stats().achievements,1);});
check('Undo restores the previous world state',()=>{g.undo();assert.equal(g.get(...target),previous);});
check('Remove block and undo removal',()=>{const hit=g.raycast(),xyz=Array.from(hit.xyz),type=hit.type;g.edit('remove');assert.equal(g.get(...xyz),0);g.undo();assert.equal(g.get(...xyz),type);});
check('Save and reload preserve construction and progress',()=>{g.choose(8);g.edit('place');g.saveNow();const again=boot(session.storage).game;assert.equal(again.get(...target),8);assert.equal(again.stats().built,2);});
check('Protected foundation cannot be removed',()=>{Object.assign(g.player,{x:1.5,y:3,z:1.5,pitch:-1.3,yaw:0});const hit=g.raycast();assert.ok(hit);assert.equal(hit.xyz[1],0);const before=g.get(...hit.xyz);g.edit('remove');assert.equal(g.get(...hit.xyz),before);});
check('Flight stops on release and stays within height limits',()=>{g.home();g.held.add('rise');for(let i=0;i<300;i++)g.move(.04);assert.ok(g.player.y<=18);g.held.clear();const height=g.player.y;g.move(.04);assert.equal(g.player.y,height);});
check('Movement respects island boundaries',()=>{Object.assign(g.player,{x:.5,y:17,z:.5,yaw:0});g.held.add('left');g.held.add('forward');for(let i=0;i<100;i++)g.move(.04);assert.ok(g.player.x>=.4 && g.player.z>=.4);g.held.clear();});
check('Malformed save does not prevent game startup',()=>{const s=new Map([['little-block-world-v1','{bad json']]);assert.ok(boot(s).game.raycast());});
check('Invalid save coordinates, foundation edits and unknown blocks are ignored',()=>{const s=new Map([['little-block-world-v1',JSON.stringify({version:1,changes:{'20,0,20':0,'100,4,5':7,'20,4,20':99,'19,4,20':7},built:-2,achievements:90})]]);const other=boot(s).game;assert.ok(other.get(20,0,20));assert.equal(other.get(19,4,20),7);assert.equal(other.stats().built,0);assert.equal(other.stats().achievements,3);});
check('Eight placements and three materials award all stars',()=>{g.home();for(let i=0;i<8;i++){g.choose([6,7,8][i%3]);g.edit('place');g.undo();}assert.ok(g.stats().built>=8);assert.equal(g.stats().achievements,3);});
check('Reset restores the original world and clears progress',()=>{g.reset();assert.equal(g.stats().built,0);assert.equal(g.stats().achievements,0);assert.equal(Object.keys(g.stats().changes).length,0);assert.equal(g.get(18,5,18),8);});
check('Context menu is blocked on the whole document',()=>{let prevented=false;session.listeners.get('contextmenu')({preventDefault:()=>prevented=true});assert.equal(prevented,true);});
check('Space ascends, Shift descends, and key defaults are prevented',()=>{g.home();const start=g.player.y;let prevented=false;g.handleKeyDown({code:'Space',repeat:false,timeStamp:1000,preventDefault:()=>prevented=true});g.move(.04);assert.ok(g.player.y>start);assert.ok(prevented);g.keys.clear();g.handleKeyDown({code:'ShiftLeft',repeat:false,timeStamp:2000,preventDefault(){}});const high=g.player.y;g.move(.04);assert.ok(g.player.y<high);g.keys.clear();});
check('Mouse offset changes the actual ray direction and selected voxel',()=>{g.home();const first=g.raycast();g.positionAim(115,0);const second=g.raycast();assert.ok(second);assert.notEqual(first.xyz.join(','),second.xyz.join(','));assert.ok(g.aimDirection()[0]>0);g.positionAim(10000,0);assert.ok(Math.hypot(g.aimOffset.x,g.aimOffset.y)<=130.001);g.home();});
check('Off-center building and removal use the visible crosshair',()=>{g.home();g.positionAim(110,20);const xyz=Array.from(g.raycast().previous);g.choose(9);g.edit('place');assert.equal(g.get(...xyz),9);g.edit('remove');assert.equal(g.get(...xyz),0);g.home();});
check('Player walks under a one-block-high ceiling and stops at a wall',()=>{const tiny=boot().game;for(let x=14;x<=17;x++)for(let z=14;z<=16;z++)tiny.set(x,4,z,5);Object.assign(tiny.player,{x:13.5,y:3.722,z:15.5,yaw:0});assert.equal(tiny.collides(14.5,3.722,15.5),false);tiny.held.add('right');for(let i=0;i<12;i++)tiny.move(.04);assert.ok(tiny.player.x>15);assert.equal(tiny.player.y,3.722);tiny.set(16,3,15,5);for(let i=0;i<15;i++)tiny.move(.04);assert.ok(tiny.player.x<16);assert.equal(tiny.collides(tiny.player.x,tiny.player.y,tiny.player.z),false);});
function shift(game,time,repeat=false) {game.handleKeyDown({code:'ShiftLeft',timeStamp:time,repeat,preventDefault(){}});}
check('Holding Shift does not trigger free fall; two separate taps do',()=>{const f=boot().game;Object.assign(f.player,{x:25.5,y:15,z:25.5});shift(f,1000);shift(f,1100,true);assert.equal(f.stats().falling,false);f.keys.clear();shift(f,1200);assert.equal(f.stats().falling,true);f.keys.clear();const high=f.player.y;f.move(.04);assert.ok(f.player.y<high);});
check('Free fall lands on solid ground without clipping through blocks',()=>{const f=boot().game;Object.assign(f.player,{x:25.5,y:18,z:25.5});shift(f,1000);f.keys.clear();shift(f,1200);f.keys.clear();for(let i=0;i<200;i++)f.move(.04);assert.equal(f.stats().falling,false);assert.ok(Math.abs(f.player.y-3.722)<1e-8);assert.equal(f.collides(f.player.x,f.player.y,f.player.z),false);});
check('Free fall lands on the roof, including high-speed swept collision',()=>{const f=boot().game;Object.assign(f.player,{x:20.5,y:18,z:18.5});shift(f,1000);f.keys.clear();shift(f,1200);f.keys.clear();for(let i=0;i<200;i++)f.move(.04);assert.ok(Math.abs(f.player.y-10.722)<1e-8);assert.equal(f.stats().falling,false);});
check('Space stops free fall; slow Shift taps do not start it',()=>{const f=boot().game;shift(f,1000);f.keys.clear();shift(f,1500);assert.equal(f.stats().falling,false);f.keys.clear();shift(f,1600);f.keys.clear();f.move(.04);f.handleKeyDown({code:'Space',timeStamp:1650,repeat:false,preventDefault(){}});f.move(.04);assert.equal(f.stats().falling,false);});
check('God view stays high, prevents editing, and returns exact position, direction and aim',()=>{g.home();g.positionAim(63,-27);Object.assign(g.player,{x:25.5,y:8.2,z:25.5,yaw:.51,pitch:-.23});const original=JSON.stringify(g.player),aim=JSON.stringify(g.aimOffset),before=Object.keys(g.stats().changes).length;g.toggleGodView();assert.equal(g.player.y,42);g.held.add('sink');g.move(.04);assert.equal(g.player.y,42);g.edit('place');assert.equal(Object.keys(g.stats().changes).length,before);g.player.yaw+=.6;g.toggleGodView();assert.equal(JSON.stringify(g.player),original);assert.equal(JSON.stringify(g.aimOffset),aim);assert.equal(g.stats().godView,null);});
check('Return home from God view resets view state and controls',()=>{g.toggleGodView();g.home();assert.equal(g.stats().godView,null);assert.equal(g.player.y,8);assert.equal(g.aimOffset.x,0);});
check('All four regions have distinct terrain, safe starts and buildable targets',()=>{const a=boot().game;for(const id of ['cottage','street','volcano','meadow']){a.switchArea(id);assert.equal(a.stats().currentArea,id);assert.equal(a.collides(a.player.x,a.player.y,a.player.z),false);assert.ok(a.raycast(),id+' should have a starting target');}a.switchArea('street');assert.equal(a.get(17,2,35),14);assert.equal(a.get(27,5,5),8);a.switchArea('volcano');assert.equal(a.get(20,5,19),15);assert.equal(a.get(24,10,19),18);a.switchArea('meadow');for(let x=0;x<40;x++)for(let z=0;z<40;z++){assert.equal(a.get(x,2,z),1);for(let y=3;y<24;y++)assert.equal(a.get(x,y,z),0);}});
check('Region switch flushes pending writes, preserves blocks, stars and independent undo',()=>{const s=boot(),a=s.game;const cottageTarget=Array.from(a.raycast().previous);a.choose(7);a.edit('place');a.switchArea('street');s.flushTimers();assert.equal(a.stats().built,0);const beforeStreet=a.raycast().xyz.join(',');a.undo();assert.equal(a.raycast().xyz.join(','),beforeStreet);const streetTarget=Array.from(a.raycast().previous);a.choose(16);a.edit('place');a.switchArea('cottage');assert.equal(a.get(...cottageTarget),7);assert.equal(a.stats().achievements,1);assert.equal(a.stats().built,1);a.undo();assert.equal(a.get(...cottageTarget),0);a.switchArea('street');assert.equal(a.get(...streetTarget),16);assert.equal(a.stats().built,1);a.undo();assert.equal(a.get(...streetTarget),0);});
check('All regional construction and last chosen area survive a fresh session',()=>{const s=boot(),targets={};for(const id of ['cottage','street','volcano','meadow']){s.game.switchArea(id);targets[id]=Array.from(s.game.raycast().previous);s.game.choose(7);s.game.edit('place');s.game.saveNow();}const fresh=boot(s.storage).game;assert.equal(fresh.stats().currentArea,'meadow');for(const id of ['cottage','street','volcano','meadow']){fresh.switchArea(id);assert.equal(fresh.get(...targets[id]),7);assert.equal(fresh.stats().built,1);assert.equal(fresh.stats().achievements,1);}});
check('New World restores only the current region and leaves every other saved region byte-identical',()=>{const s=boot(),a=s.game;for(const id of ['cottage','street','volcano','meadow']){a.switchArea(id);a.choose(7);a.edit('place');a.saveNow();}a.switchArea('volcano');const others=['cottage','street','meadow'].map(id=>[id,s.storage.get(a.saveKey(id))]);a.reset();assert.equal(a.stats().built,0);assert.equal(a.get(20,5,19),15);for(const [id,raw]of others)assert.equal(s.storage.get(a.saveKey(id)),raw);const fresh=boot(s.storage).game;fresh.switchArea('volcano');assert.equal(fresh.stats().built,0);for(const [id]of others){fresh.switchArea(id);assert.equal(fresh.stats().built,1);assert.equal(fresh.stats().achievements,1);}});
check('Legacy cottage save migrates without changing its backup and cannot reappear after reset',()=>{const legacy=JSON.stringify({version:1,changes:{'19,4,20':7},built:8,colors:[6,7,8],achievements:3});const s=boot(new Map([['little-block-world-v1',legacy]])),a=s.game;assert.equal(a.get(19,4,20),7);assert.equal(a.stats().achievements,3);assert.equal(s.storage.get('little-block-world-v1'),legacy);assert.equal(JSON.parse(s.storage.get(a.saveKey())).version,2);a.switchArea('meadow');a.reset();a.switchArea('cottage');assert.equal(a.get(19,4,20),7);a.reset();a.switchArea('street');a.switchArea('cottage');assert.equal(a.get(19,4,20),0);assert.equal(boot(s.storage).game.get(19,4,20),0);assert.equal(s.storage.get('little-block-world-v1'),legacy);});
check('The same coordinates can hold different materials in different regions',()=>{const s=boot(),a=s.game;Object.assign(a.player,{x:20.5,y:4.722,z:20.5,pitch:-1.2});a.switchArea('meadow');const xyz=Array.from(a.raycast().previous);a.choose(8);a.edit('place');a.switchArea('street');const before=a.get(...xyz);assert.notEqual(before,8);a.switchArea('meadow');assert.equal(a.get(...xyz),8);});
check('In-memory regional work remains isolated when localStorage writes fail',()=>{class FailingStorage extends Map{set(){throw Error('Quota exceeded');}}const s=boot(new FailingStorage()),a=s.game;const xyz=Array.from(a.raycast().previous);a.choose(7);a.edit('place');assert.equal(a.saveNow(),false);a.switchArea('meadow');a.choose(8);a.edit('place');a.switchArea('cottage');assert.equal(a.get(...xyz),7);assert.equal(a.stats().built,1);a.switchArea('meadow');assert.equal(a.stats().built,1);});
check('R selects generated materials and number keys match the current palette tab',()=>{const a=boot().game;a.switchArea('street');a.pickBlock();assert.equal(a.stats().selected,a.raycast().type);a.renderPalette('nature');a.handleKeyDown({code:'Digit7',key:'7',repeat:false,timeStamp:2000,preventDefault(){}});assert.equal(a.stats().selected,18);a.renderPalette('building');a.handleKeyDown({code:'Digit7',key:'7',repeat:false,timeStamp:3000,preventDefault(){}});assert.equal(a.stats().selected,17);});
check('God view is excluded from saved positions and changing regions exits it',()=>{const s=boot(),a=s.game;const before={...a.player};a.toggleGodView();a.saveNow();const payload=JSON.parse(s.storage.get(a.saveKey()));assert.equal(payload.player.y,before.y);a.switchArea('volcano');assert.equal(a.stats().godView,null);assert.equal(a.player.y,17.5);a.switchArea('cottage');assert.equal(a.player.y,before.y);});
check('Invalid region selection or mismatched save identity cannot replace another region',()=>{const s=boot(),a=s.game;a.switchArea('__proto__');assert.equal(a.stats().currentArea,'cottage');s.storage.set(a.saveKey('meadow'),JSON.stringify({version:2,area:'street',changes:{'20,3,20':7},built:4}));a.switchArea('meadow');assert.equal(a.stats().built,0);assert.equal(a.get(20,3,20),0);});
console.log(`${checks} behavioral checks passed.`);
