const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(require('node:path').join(__dirname, '..', 'game.js'), 'utf8').replace(/\}\)\(\);\s*$/, `
  globalThis.testGame = { get, set, raycast, edit, undo, choose, saveNow, home, move, viewProjection, rebuild, player, keys, held,
    collides, lowerTo, positionAim, aimDirection, aimOffset, handleKeyDown, toggleGodView,
    switchArea, saveKey, pickBlock, renderPalette, updateBombs, bombs, frame,
    history: () => history,
    start: () => started = true,
    stats: () => ({built, colors: [...usedColors], achievements, changes, meshCount, falling, godView, currentArea, selected, paletteGroup}),
    reset: () => $('confirm-reset').onclick() };
})();`);
function boot(storage = new Map()) {
  const elements = new Map();
  const listeners = new Map();
  const timers = new Map();let nextTimer=1;
  const ctx2d = {setTransform(){},clearRect(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},stroke(){},fillRect(){},fillText(){}};
  const gl = new Proxy({}, { get: (_, key) => {
    if (key === 'getShaderParameter' || key === 'getProgramParameter') return () => true;
    if (key === 'getAttribLocation') return () => 1;
    if (key === 'createProgram' || key === 'createShader' || key === 'createBuffer') return () => ({});
    return () => {};
  }});
  function element(id) {
    if (!elements.has(id)) elements.set(id, {textContent:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(){},appendChild(){},getContext:type=>type==='2d'?ctx2d:gl});
    return elements.get(id);
  }
  let modal=false;
  const context = {document:{visibilityState:'visible',getElementById:element,querySelector:()=>modal?{}:null,querySelectorAll:()=>[],createElement:()=>element('temp'+Math.random()),addEventListener:(name,fn)=>listeners.set(name,fn)},window:{devicePixelRatio:1,addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},console,setTimeout:fn=>{const id=nextTimer++;timers.set(id,fn);return id;},clearTimeout:id=>timers.delete(id),requestAnimationFrame(){},innerWidth:1300,innerHeight:880};
  vm.createContext(context);vm.runInContext(source,context);context.testGame.start();
  return {game:context.testGame,elements,storage,listeners,setModal:v=>modal=v,setHidden:v=>{context.document.visibilityState=v?'hidden':'visible';listeners.get('visibilitychange')();},flushTimers:()=>{const pending=[...timers.entries()];timers.clear();pending.forEach(([,fn])=>fn());}};
}
let checks=0;
function check(label, fn) { fn(); checks++; console.log('PASS '+label); }
const session=boot(),g=session.game;
check('Initial world includes a house, pond and protected foundation',()=>{assert.equal(g.get(18,5,18),8);assert.equal(g.get(10,1,21),10);assert.ok(g.get(20,0,20));});
check('Starting camera immediately targets a buildable surface',()=>{const hit=g.raycast();assert.ok(hit);assert.ok(hit.distance<16);assert.ok(hit.previous[1]>0);});
check('Projection is finite and mesh contains visible triangles',()=>{assert.ok([...g.viewProjection()].every(Number.isFinite));g.rebuild();assert.ok(g.stats().meshCount>1000);assert.equal(g.stats().meshCount%3,0);});
const target=Array.from(g.raycast().previous),previous=g.get(...target);
check('Place selected block and award the first star',()=>{g.choose(7);g.edit('place');assert.equal(g.get(...target),7);assert.equal(g.stats().built,1);assert.equal(g.stats().achievements,1);});
check('Undo restores the previous world state',()=>{g.undo();assert.equal(g.get(...target),previous);});
check('Remove block and undo removal',()=>{const hit=g.raycast(),xyz=Array.from(hit.xyz),type=hit.type;g.edit('remove');assert.equal(g.get(...xyz),0);g.undo();assert.equal(g.get(...xyz),type);});
check('Save and reload preserve construction and progress',()=>{g.choose(8);g.edit('place');g.saveNow();const again=boot(session.storage).game;assert.equal(again.get(...target),8);assert.equal(again.stats().built,2);});
check('Protected foundation cannot be removed',()=>{Object.assign(g.player,{x:1.5,y:3,z:1.5,pitch:-1.3,yaw:0});const hit=g.raycast();assert.ok(hit);assert.equal(hit.xyz[1],0);const before=g.get(...hit.xyz);g.edit('remove');assert.equal(g.get(...hit.xyz),before);});
check('Flight stops on release and stays within height limits',()=>{g.home();g.held.add('rise');for(let i=0;i<300;i++)g.move(.04);assert.ok(g.player.y<=38);g.held.clear();const height=g.player.y;g.move(.04);assert.equal(g.player.y,height);});
check('Movement respects island boundaries',()=>{Object.assign(g.player,{x:.5,y:17,z:.5,yaw:0});g.held.add('left');g.held.add('forward');for(let i=0;i<100;i++)g.move(.04);assert.ok(g.player.x>=.4 && g.player.z>=.4);g.held.clear();});
check('Malformed save does not prevent game startup',()=>{const s=new Map([['little-block-world-v1','{bad json']]);assert.ok(boot(s).game.raycast());});
check('Invalid save coordinates, foundation edits and unknown blocks are ignored',()=>{const s=new Map([['little-block-world-v1',JSON.stringify({version:1,changes:{'20,0,20':0,'100,4,5':7,'20,4,20':99,'19,4,20':7},built:-2,achievements:90})]]);const other=boot(s).game;assert.ok(other.get(20,0,20));assert.equal(other.get(19,4,20),7);assert.equal(other.stats().built,0);assert.equal(other.stats().achievements,3);});
check('Eight placements and three materials award all stars',()=>{g.home();for(let i=0;i<8;i++){g.choose([6,7,8][i%3]);g.edit('place');g.undo();}assert.ok(g.stats().built>=8);assert.equal(g.stats().achievements,3);});
check('Reset restores the original world and clears progress',()=>{g.reset();assert.equal(g.stats().built,0);assert.equal(g.stats().achievements,0);assert.equal(Object.keys(g.stats().changes).length,0);assert.equal(g.get(18,5,18),8);});
check('Context menu is blocked on the whole document',()=>{let prevented=false;session.listeners.get('contextmenu')({preventDefault:()=>prevented=true});assert.equal(prevented,true);});
check('Space ascends, Shift descends, and key defaults are prevented',()=>{g.home();const start=g.player.y;let prevented=false;g.handleKeyDown({code:'Space',repeat:false,timeStamp:1000,preventDefault:()=>prevented=true});g.move(.04);assert.ok(g.player.y>start);assert.ok(prevented);g.keys.clear();g.handleKeyDown({code:'ShiftLeft',repeat:false,timeStamp:2000,preventDefault(){}});const high=g.player.y;g.move(.04);assert.ok(g.player.y<high);g.keys.clear();});
check('Mouse offset changes the actual ray direction and selected voxel',()=>{g.home();const first=g.raycast();g.positionAim(115,0);const second=g.raycast();assert.ok(second);assert.notEqual(first.xyz.join(','),second.xyz.join(','));assert.ok(g.aimDirection()[0]>0);g.positionAim(10000,0);assert.ok(Math.hypot(g.aimOffset.x,g.aimOffset.y)<=130.001);g.home();});
check('Off-center building and removal use the visible crosshair',()=>{g.home();g.positionAim(110,20);const xyz=Array.from(g.raycast().previous);g.choose(9);g.edit('place');assert.equal(g.get(...xyz),9);g.edit('remove');assert.equal(g.get(...xyz),0);g.home();});
check('Player walks under a one-block-high ceiling and stops at a wall',()=>{const tiny=boot().game;for(let x=14;x<=17;x++)for(let z=14;z<=16;z++)tiny.set(x,4,z,5);Object.assign(tiny.player,{x:13.5,y:3.722,z:15.5,yaw:0});assert.equal(tiny.collides(14.5,3.722,15.5),false);tiny.held.add('right');for(let i=0;i<12;i++)tiny.move(.04);assert.ok(tiny.player.x>15);assert.equal(tiny.player.y,3.722);tiny.set(16,3,15,5);for(let i=0;i<15;i++)tiny.move(.04);assert.ok(tiny.player.x<16);assert.equal(tiny.collides(tiny.player.x,tiny.player.y,tiny.player.z),false);});
function shift(game,time,repeat=false) {game.handleKeyDown({code:'ShiftLeft',timeStamp:time,repeat,preventDefault(){}});}
check('Holding Shift does not trigger free fall; two separate taps do',()=>{const f=boot().game;Object.assign(f.player,{x:25.5,y:15,z:25.5});shift(f,1000);shift(f,1100,true);assert.equal(f.stats().falling,false);f.keys.clear();shift(f,1200);assert.equal(f.stats().falling,true);f.keys.clear();const high=f.player.y;f.move(.04);assert.ok(f.player.y<high);});
check('Free fall lands on solid ground without clipping through blocks',()=>{const f=boot().game;Object.assign(f.player,{x:25.5,y:18,z:25.5});shift(f,1000);f.keys.clear();shift(f,1200);f.keys.clear();for(let i=0;i<200;i++)f.move(.04);assert.equal(f.stats().falling,false);assert.ok(Math.abs(f.player.y-3.722)<1e-8);assert.equal(f.collides(f.player.x,f.player.y,f.player.z),false);});
check('Free fall lands on the roof, including high-speed swept collision',()=>{const f=boot().game;Object.assign(f.player,{x:20.5,y:18,z:18.5});shift(f,1000);f.keys.clear();shift(f,1200);f.keys.clear();for(let i=0;i<200;i++)f.move(.04);assert.ok(Math.abs(f.player.y-10.722)<1e-8);assert.equal(f.stats().falling,false);});
check('Space stops free fall; slow Shift taps do not start it',()=>{const f=boot().game;shift(f,1000);f.keys.clear();shift(f,1500);assert.equal(f.stats().falling,false);f.keys.clear();shift(f,1600);f.keys.clear();f.move(.04);f.handleKeyDown({code:'Space',timeStamp:1650,repeat:false,preventDefault(){}});f.move(.04);assert.equal(f.stats().falling,false);});
check('God view stays high, prevents editing, and returns exact position, direction and aim',()=>{g.home();g.positionAim(63,-27);Object.assign(g.player,{x:25.5,y:8.2,z:25.5,yaw:.51,pitch:-.23});const original=JSON.stringify(g.player),aim=JSON.stringify(g.aimOffset),before=Object.keys(g.stats().changes).length;g.toggleGodView();assert.equal(g.player.y,42);g.held.add('sink');g.move(.04);assert.equal(g.player.y,42);g.edit('place');assert.equal(Object.keys(g.stats().changes).length,before);g.player.yaw+=.6;g.toggleGodView();assert.equal(JSON.stringify(g.player),original);assert.equal(JSON.stringify(g.aimOffset),aim);assert.equal(g.stats().godView,null);});
check('Return home from God view resets view state and controls',()=>{g.toggleGodView();g.home();assert.equal(g.stats().godView,null);assert.equal(g.player.y,8);assert.equal(g.aimOffset.x,0);});
check('All seven regions have distinct terrain, safe starts and buildable targets',()=>{const a=boot().game;for(const id of ['cottage','street','volcano','meadow','titanic','cars','taipei101']){a.switchArea(id);assert.equal(a.stats().currentArea,id);assert.equal(a.collides(a.player.x,a.player.y,a.player.z),false);assert.ok(a.raycast(),id+' should have a starting target');}a.switchArea('street');assert.equal(a.get(17,2,35),14);assert.equal(a.get(27,5,5),8);a.switchArea('volcano');assert.equal(a.get(20,5,19),15);assert.equal(a.get(24,10,19),18);a.switchArea('meadow');for(let x=0;x<40;x++)for(let z=0;z<40;z++){assert.equal(a.get(x,2,z),1);for(let y=3;y<40;y++)assert.equal(a.get(x,y,z),0);}});
check('Region switch flushes pending writes, preserves blocks, stars and independent undo',()=>{const s=boot(),a=s.game;const cottageTarget=Array.from(a.raycast().previous);a.choose(7);a.edit('place');a.switchArea('street');s.flushTimers();assert.equal(a.stats().built,0);const beforeStreet=a.raycast().xyz.join(',');a.undo();assert.equal(a.raycast().xyz.join(','),beforeStreet);const streetTarget=Array.from(a.raycast().previous);a.choose(16);a.edit('place');a.switchArea('cottage');assert.equal(a.get(...cottageTarget),7);assert.equal(a.stats().achievements,1);assert.equal(a.stats().built,1);a.undo();assert.equal(a.get(...cottageTarget),0);a.switchArea('street');assert.equal(a.get(...streetTarget),16);assert.equal(a.stats().built,1);a.undo();assert.equal(a.get(...streetTarget),0);});
check('All regional construction and last chosen area survive a fresh session',()=>{const s=boot(),targets={};for(const id of ['cottage','street','volcano','meadow','titanic','cars','taipei101']){s.game.switchArea(id);targets[id]=Array.from(s.game.raycast().previous);s.game.choose(7);s.game.edit('place');s.game.saveNow();}const fresh=boot(s.storage).game;assert.equal(fresh.stats().currentArea,'taipei101');for(const id of ['cottage','street','volcano','meadow','titanic','cars','taipei101']){fresh.switchArea(id);assert.equal(fresh.get(...targets[id]),7);assert.equal(fresh.stats().built,1);assert.equal(fresh.stats().achievements,1);}});
check('New World restores only the current region and leaves every other saved region byte-identical',()=>{const s=boot(),a=s.game;for(const id of ['cottage','street','volcano','meadow','titanic','cars','taipei101']){a.switchArea(id);a.choose(7);a.edit('place');a.saveNow();}a.switchArea('volcano');const others=['cottage','street','meadow','titanic','cars','taipei101'].map(id=>[id,s.storage.get(a.saveKey(id))]);a.reset();assert.equal(a.stats().built,0);assert.equal(a.get(20,5,19),15);for(const [id,raw]of others)assert.equal(s.storage.get(a.saveKey(id)),raw);const fresh=boot(s.storage).game;fresh.switchArea('volcano');assert.equal(fresh.stats().built,0);for(const [id]of others){fresh.switchArea(id);assert.equal(fresh.stats().built,1);assert.equal(fresh.stats().achievements,1);}});
check('Legacy cottage save migrates without changing its backup and cannot reappear after reset',()=>{const legacy=JSON.stringify({version:1,changes:{'19,4,20':7},built:8,colors:[6,7,8],achievements:3});const s=boot(new Map([['little-block-world-v1',legacy]])),a=s.game;assert.equal(a.get(19,4,20),7);assert.equal(a.stats().achievements,3);assert.equal(s.storage.get('little-block-world-v1'),legacy);assert.equal(JSON.parse(s.storage.get(a.saveKey())).version,2);a.switchArea('meadow');a.reset();a.switchArea('cottage');assert.equal(a.get(19,4,20),7);a.reset();a.switchArea('street');a.switchArea('cottage');assert.equal(a.get(19,4,20),0);assert.equal(boot(s.storage).game.get(19,4,20),0);assert.equal(s.storage.get('little-block-world-v1'),legacy);});
check('The same coordinates can hold different materials in different regions',()=>{const s=boot(),a=s.game;Object.assign(a.player,{x:20.5,y:4.722,z:20.5,pitch:-1.2});a.switchArea('meadow');const xyz=Array.from(a.raycast().previous);a.choose(8);a.edit('place');a.switchArea('street');const before=a.get(...xyz);assert.notEqual(before,8);a.switchArea('meadow');assert.equal(a.get(...xyz),8);});
check('In-memory regional work remains isolated when localStorage writes fail',()=>{class FailingStorage extends Map{set(){throw Error('Quota exceeded');}}const s=boot(new FailingStorage()),a=s.game;const xyz=Array.from(a.raycast().previous);a.choose(7);a.edit('place');assert.equal(a.saveNow(),false);a.switchArea('meadow');a.choose(8);a.edit('place');a.switchArea('cottage');assert.equal(a.get(...xyz),7);assert.equal(a.stats().built,1);a.switchArea('meadow');assert.equal(a.stats().built,1);});
check('R selects generated materials and number keys match the current palette tab',()=>{const a=boot().game;a.switchArea('street');a.pickBlock();assert.equal(a.stats().selected,a.raycast().type);a.renderPalette('nature');a.handleKeyDown({code:'Digit7',key:'7',repeat:false,timeStamp:2000,preventDefault(){}});assert.equal(a.stats().selected,18);a.renderPalette('building');a.handleKeyDown({code:'Digit7',key:'7',repeat:false,timeStamp:3000,preventDefault(){}});assert.equal(a.stats().selected,17);});
check('God view is excluded from saved positions and changing regions exits it',()=>{const s=boot(),a=s.game;const before={...a.player};a.toggleGodView();a.saveNow();const payload=JSON.parse(s.storage.get(a.saveKey()));assert.equal(payload.player.y,before.y);a.switchArea('volcano');assert.equal(a.stats().godView,null);assert.equal(a.player.y,17.5);a.switchArea('cottage');assert.equal(a.player.y,before.y);});
check('Invalid region selection or mismatched save identity cannot replace another region',()=>{const s=boot(),a=s.game;a.switchArea('__proto__');assert.equal(a.stats().currentArea,'cottage');s.storage.set(a.saveKey('meadow'),JSON.stringify({version:2,area:'street',changes:{'20,3,20':7},built:4}));a.switchArea('meadow');assert.equal(a.stats().built,0);assert.equal(a.get(20,3,20),0);});
function plant(game,area='meadow') {
  game.switchArea(area);game.choose(19);const xyz=Array.from(game.raycast().previous);game.edit('place');
  assert.equal(game.get(...xyz),19);assert.equal(game.bombs.get(xyz.join(',')).remaining,10);return xyz;
}
function worldState(game){const result=[];for(let y=0;y<40;y++)for(let z=0;z<40;z++)for(let x=0;x<40;x++)result.push(game.get(x,y,z));return result;}
check('Landmarks have four funnels, different vehicles and an eight-tier tower with a tall spire',()=>{const a=boot().game;a.switchArea('titanic');for(const z of [12,17,22,26]){assert.equal(a.get(20,14,z),9);assert.equal(a.get(20,17,z),18);}assert.equal(a.get(15,5,20),14);a.switchArea('cars');assert.equal(a.get(19,6,25),9);assert.equal(a.get(29,7,29),16);assert.equal(a.get(24,9,30),14);a.switchArea('taipei101');for(let i=0;i<8;i++)assert.equal(a.get(16,10+i*3,20),20);assert.equal(a.get(20,38,20),12);assert.equal(a.get(20,4,25),0);a.rebuild();assert.ok(a.stats().meshCount>1000);});
check('Bomb placement arms exactly ten seconds and explodes only when the countdown ends',()=>{const a=boot().game,xyz=plant(a);a.updateBombs(9);assert.equal(a.get(...xyz),19);assert.equal(a.bombs.get(xyz.join(',')).remaining,1);a.updateBombs(.5);assert.equal(a.get(...xyz),19);a.updateBombs(.5);assert.equal(a.get(...xyz),0);assert.equal(a.bombs.size,0);assert.equal(a.history().at(-1).kind,'explosion');});
check('Blast removes a two-block sphere, leaves its foundation and distant blocks intact, and never moves the player',()=>{const a=boot().game,[x,y,z]=plant(a);for(const [dx,dy,dz]of [[2,0,0],[2,1,0],[-2,0,0],[0,0,2],[1,1,1]])a.set(x+dx,y+dy,z+dz,6);const camera=JSON.stringify(a.player),base=worldState(a).slice(0,1600);a.updateBombs(10);assert.equal(a.get(x+2,y,z),0);assert.equal(a.get(x+2,y+1,z),6);assert.equal(a.get(x-2,y,z),0);assert.equal(a.get(x+1,y+1,z+1),0);assert.equal(JSON.stringify(a.player),camera);assert.deepEqual(worldState(a).slice(0,1600),base);});
check('One undo restores the entire explosion and disarms restored bombs',()=>{const a=boot().game,xyz=plant(a);const before=worldState(a);a.updateBombs(10);assert.notDeepEqual(worldState(a),before);a.undo();assert.deepEqual(worldState(a),before);assert.equal(a.get(...xyz),19);assert.equal(a.bombs.size,0);a.updateBombs(30);assert.deepEqual(worldState(a),before);a.undo();assert.equal(a.get(...xyz),0);});
check('Removing a live bomb cancels it; undoing removal restores a stopped bomb',()=>{const a=boot().game,xyz=plant(a);a.updateBombs(3);a.edit('remove');assert.equal(a.get(...xyz),0);assert.equal(a.bombs.size,0);a.undo();assert.equal(a.get(...xyz),19);assert.equal(a.bombs.size,0);const before=worldState(a);a.updateBombs(20);assert.deepEqual(worldState(a),before);});
check('Undoing a bomb placement cancels its future explosion',()=>{const a=boot().game;plant(a);a.undo();const before=worldState(a);a.updateBombs(20);assert.equal(a.bombs.size,0);assert.deepEqual(worldState(a),before);});
check('Nearby bombs are canceled without a chain reaction and other distant timers continue',()=>{const a=boot().game,[x,y,z]=plant(a);for(const offset of [1,3]){const xyz=[x+offset,y,z];a.set(...xyz,19);a.bombs.set(xyz.join(','),{xyz,remaining:10});}a.bombs.get([x,y,z].join(',')).remaining=1;a.updateBombs(1);assert.equal(a.get(x+1,y,z),0);assert.equal(a.get(x+3,y,z),19);assert.equal(a.bombs.size,1);assert.equal(a.bombs.get([x+3,y,z].join(',')).remaining,9);assert.equal(a.history().filter(i=>i.kind==='explosion').length,1);});
check('Countdown pauses behind dialogs and in hidden tabs, then resumes without counting hidden time',()=>{const s=boot(),a=s.game,xyz=plant(a);a.frame(1000);a.frame(3000);assert.equal(a.bombs.get(xyz.join(',')).remaining,8);s.setModal(true);a.frame(13000);assert.equal(a.bombs.get(xyz.join(',')).remaining,8);s.setModal(false);a.frame(14000);assert.equal(a.bombs.get(xyz.join(',')).remaining,7);s.setHidden(true);a.frame(20000);assert.equal(a.bombs.get(xyz.join(',')).remaining,7);s.setHidden(false);a.frame(90000);a.frame(91000);assert.equal(a.bombs.get(xyz.join(',')).remaining,6);});
check('Each area preserves its remaining countdown independently, including across reloads',()=>{const s=boot(),a=s.game,meadow=plant(a);a.updateBombs(4);const ship=plant(a,'titanic');a.updateBombs(2);a.switchArea('meadow');assert.equal(a.bombs.get(meadow.join(',')).remaining,6);a.switchArea('titanic');assert.equal(a.bombs.get(ship.join(',')).remaining,8);a.saveNow();const fresh=boot(s.storage).game;assert.equal(fresh.stats().currentArea,'titanic');assert.equal(fresh.bombs.get(ship.join(',')).remaining,8);fresh.switchArea('meadow');assert.equal(fresh.bombs.get(meadow.join(',')).remaining,6);fresh.updateBombs(6);fresh.switchArea('titanic');assert.equal(fresh.get(...ship),19);assert.equal(fresh.bombs.get(ship.join(',')).remaining,8);});
check('Reset clears only current bombs and retains the other region countdown and saved bytes',()=>{const s=boot(),a=s.game;const meadow=plant(a);a.updateBombs(3);plant(a,'cars');const raw=s.storage.get(a.saveKey('meadow'));a.reset();assert.equal(a.bombs.size,0);assert.equal(s.storage.get(a.saveKey('meadow')),raw);a.switchArea('meadow');assert.equal(a.get(...meadow),19);assert.equal(a.bombs.get(meadow.join(',')).remaining,7);});
check('Invalid saved timers do not arm unknown, out-of-range or stopped blocks',()=>{const payload={version:2,area:'meadow',changes:{'10,4,10':19},bombs:[{xyz:[10,4,10],remaining:99},{xyz:[9,4,9],remaining:5},{xyz:[10,4,10],remaining:-1},{xyz:[10,4,10],remaining:'5'},{xyz:[10,4,10,10],remaining:5}],selected:19};const a=boot(new Map([['little-block-world-area-v2','meadow'],['little-block-world-v2:meadow',JSON.stringify(payload)]])).game;assert.equal(a.get(10,4,10),19);assert.equal(a.bombs.size,0);assert.equal(a.stats().paletteGroup,'fun');a.updateBombs(100);assert.equal(a.get(10,4,10),19);});
check('Countdown edits and grouped explosion undo remain isolated in memory when storage fails',()=>{class FailingStorage extends Map{set(){throw Error('Quota exceeded');}}const s=boot(new FailingStorage()),a=s.game,xyz=plant(a);a.updateBombs(2);a.switchArea('cars');a.switchArea('meadow');assert.equal(a.bombs.get(xyz.join(',')).remaining,8);const before=worldState(a);a.updateBombs(8);a.switchArea('cars');a.switchArea('meadow');a.undo();assert.deepEqual(worldState(a),before);assert.equal(a.bombs.size,0);});
check('High flying camera and construction above the old ceiling survive a fresh session',()=>{const s=boot(),a=s.game;a.switchArea('taipei101');Object.assign(a.player,{x:29.5,y:36,z:30.5,yaw:-.73,pitch:-.42});const xyz=Array.from(a.raycast().previous);assert.ok(xyz[1]>24);a.choose(7);a.edit('place');assert.equal(a.get(...xyz),7);a.saveNow();const fresh=boot(s.storage).game;assert.equal(fresh.get(...xyz),7);assert.equal(fresh.player.y,36);fresh.toggleGodView();assert.equal(fresh.player.y,70);assert.ok([...fresh.viewProjection()].every(Number.isFinite));fresh.toggleGodView();assert.equal(fresh.player.y,36);});
console.log(`${checks} behavioral checks passed.`);
